### PR TITLE
Mutations

### PR DESCRIPTION
**Pull request by justinvdh**
Complex mutations will now be found and collapsed.
Fixed a bug concerning the interaction between collapsing point mutations and deletion mutations.

### CODE REVIEW

**Comment by M4rissa** [comment]
View doesn't adjust properly to the new more complex mutations.

**Comment by M4rissa** [comment]
View now adjusts width properly. No further issues spotted.

**Comment by Keraito** [comment]
On 38 strains data set, when most zoomed out 2 nodes are on the same spot. Also is it intended that on most zoomed out level there is so little amount of nodes? Besides these points i think it's fine,

**Comment by justinvdh** [comment]
Several nodes being on the same spot is an old issue related to the vertical placing of the nodes. This has been assigned to a different task this sprint.

In its current state it is intended that there are so little nodes. The points system does not yet interact with every type of mutation, so every mutation that we can collapse will be collapsed in the most zoomed out level. There are a few mutations that simply cannot be collapsed with the way we find mutations, which is why there are still some mutations visible.

**Pull request merged**
